### ISSUE TITLE
ImportError in client.py

### ISSUE THREAD

**Issue by cbrichford** [jettify/aiobotocore#14]
Steps to reproduce:

1. create a fresh virtualenv: ```virtualenv -p /usr/local/bin/python3 ab```
2. install aiobotocore:

    ```
    ./ab/bin/pip install --upgrade --no-cache-dir git+https://github.com/jettify/aiobotocore.git@master#egg=aiobotocore
    ```
3. Try to import aiobotocore: ```./ab/bin/python -c 'import aiobotocore'```

Output:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "~/ab/lib/python3.5/site-packages/aiobotocore/__init__.py", line 3, in <module>
    from .session import get_session, AioSession
  File "~/ab/lib/python3.5/site-packages/aiobotocore/session.py", line 6, in <module>
    from .client import AioClientCreator
  File "~/ab/lib/python3.5/site-packages/aiobotocore/client.py", line 2, in <module>
    from botocore.utils import get_service_module_name
ImportError: cannot import name 'get_service_module_name'
```

The root cause seems to be the fact that get_service_module_name is referenced despite not existing in botocore 1.1.7 which aiobotocore specifies in the install_requires variable of setup.py.  This issue can be worked around by manually upgrading botocore to 1.2.2 or greater.

**Comment by jettify** [comment]
Thanks for detailed report! Fixed in https://github.com/jettify/aiobotocore/pull/15
